B1_배포테스트2

diff --git a/.github/workflows/test-actions.yml b/.github/workflows/test-actions.yml
--- a/.github/workflows/test-actions.yml
+++ b/.github/workflows/test-actions.yml
@@ -47,10 +47,10 @@ jobs:
             echo "Failed React"
           fi
 
-        # 백엔드 실행
-        # - name: Run Node
-        #   run: (ls /rootfit_server && echo Successed Node) || (echo Failed Node)
-        # 프론트 실행
-        # - name: Run React
-        #   run: (ls /rootfit_front && echo Successed React) || (echo Failed React)
+      # 백엔드 실행
+      # - name: Run Node
+      #   run: (ls /rootfit_server && echo Successed Node) || (echo Failed Node)
+      # 프론트 실행
+      # - name: Run React
+      #   run: (ls /rootfit_front && echo Successed React) || (echo Failed React)
     
